### ISSUE TITLE
Uncaught Error: watch ~/projects ENOSPC

### ISSUE THREAD

**Issue by mjoossen** [lloiser/go-debug#114] opened 2017-10-20 07:51 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [go-debug](https://github.com/lloiser/go-debug) package 1.5.2

### Stack Trace

Uncaught Error: watch /home/matthieu/projects ENOSPC

```
At events.js:160

Error: watch /home/matthieu/projects ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1316:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at /packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at /packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
     -0:13.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
busy-signal 1.4.3 
file-icons 2.1.13 
go-debug 1.5.2 
go-plus 5.5.6 
go-signature-statusbar 1.2.3 
hyperclick 0.1.5 
intentions 1.1.5 
language-docker 1.1.8 
linter 2.2.0 
linter-ui-default 1.6.10 
```

**Comment by lloiser** [comment] 2017-11-06 16:55
Duplicate of https://github.com/lloiser/go-debug/issues/73. If not reopen and provide more info.

**Closed by lloiser** 2017-11-06 16:55 UTC
