### ISSUE TITLE
Uncaught Error: watch ~/.go/src/github.com/mojlighetsministeriet/rsa-private-key-generator ENOSPC

### ISSUE THREAD

**Issue by tirithen** [lloiser/go-debug#116] opened 2017-11-05 11:26 UTC
[Enter steps to reproduce:]

1. Removed Atom and all settings
2. Installed packages below
3. Installed go-debug package

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: "Arch Linux"
**Thrown From**: [go-debug](https://github.com/lloiser/go-debug) package 1.5.2

### Stack Trace

Uncaught Error: watch /home/tirithen/.go/src/github.com/mojlighetsministeriet/rsa-private-key-generator ENOSPC

```
At events.js:160

Error: watch /home/tirithen/.go/src/github.com/mojlighetsministeriet/rsa-private-key-generator ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1316:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at /packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at /packages/go-debug/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
     -0:29 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-json 5.5.0 
autocomplete-modules 1.8.0 
busy-signal 1.4.3 
git-plus 7.10.0 
git-time-machine 1.5.9 
go-debug 1.5.2 
go-imports 0.1.1 
go-plus 5.6.0 
go-signature-statusbar 1.2.3 
hyperclick 0.1.5 
intentions 1.1.5 
language-docker 1.1.8 
language-nginx 0.8.0 
language-polymer 0.8.4 
linter 2.2.0 
linter-docker 0.2.1 
linter-golinter 1.2.2 
linter-polymer 0.0.3 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-git-diff 4.3.1 
minimap-linter 2.1.3 
node-debugger 1.10.1 
polymer-ide 0.4.0 
tree-view-git-status 1.4.0 
```

**Comment by lloiser** [comment] 2017-11-06 16:53
Duplicate of https://github.com/lloiser/go-debug/issues/73. If not reopen and provide more info.

**Closed by lloiser** 2017-11-06 16:53 UTC
